-- Translate factory defaults only. Keep user edits and deleted rows unchanged.

PRAGMA foreign_keys = ON;

UPDATE notebooks SET name = 'Inbox' WHERE slug = 'inbox' AND name = '等待分类';

UPDATE notebooks SET name = 'Work Projects' WHERE slug = 'work-projects' AND name = '工作项目';

UPDATE notebooks SET name = 'Learning Resources' WHERE slug = 'learning-resources' AND name = '学习资料';

UPDATE notebooks SET name = 'Creative Ideas' WHERE slug = 'creative-ideas' AND name = '灵感创作';

UPDATE notebooks SET name = 'Personal Life' WHERE slug = 'personal-life' AND name = '生活个人';

UPDATE memo_templates SET name = 'Quick Spark', title = 'Quick Spark', description = 'Capture fleeting thoughts, ideas, links, and immediate action items.', content_markdown = '## 💡 Fleeting Thoughts' || char(10) || '' || char(10) || '- ' || char(10) || '' || char(10) || '## 📌 Context & Notes' || char(10) || '' || char(10) || '' || char(10) || '' || char(10) || '## 🚀 Next Actions' || char(10) || '' || char(10) || '- [ ] ', content_json = '{"type":"doc","content":[]}' WHERE id = workspace_id || '_template_quick-note' AND name = '灵感速记' AND title = '灵感速记' AND description = '快速捕捉闪念、临时灵感、资料链接与即刻行动。' AND content_markdown = '## 💡 闪念记录' || char(10) || '' || char(10) || '- ' || char(10) || '' || char(10) || '## 📌 背景与补充说明' || char(10) || '' || char(10) || '' || char(10) || '' || char(10) || '## 🚀 下一步动作' || char(10) || '' || char(10) || '- [ ] ' AND updated_at = created_at;

UPDATE memo_templates SET name = 'Meeting Minutes', title = 'Meeting Minutes', description = 'Structured log for agenda, key decisions, and action items with owners.', content_markdown = '# 📝 Meeting Minutes' || char(10) || '' || char(10) || '- **Time**:' || char(10) || '- **Host/Recorder**:' || char(10) || '- **Attendees**:' || char(10) || '' || char(10) || '---' || char(10) || '' || char(10) || '## 🎯 Goal' || char(10) || '' || char(10) || '- ' || char(10) || '' || char(10) || '## 💬 Discussion & Decisions' || char(10) || '' || char(10) || '1. **[Topic 1]**' || char(10) || '   - Points:' || char(10) || '   - ✅ **Decision**:' || char(10) || '' || char(10) || '2. **[Topic 2]**' || char(10) || '   - Points:' || char(10) || '   - ✅ **Decision**:' || char(10) || '' || char(10) || '## 📋 Action Items' || char(10) || '' || char(10) || '- [ ] **[Owner]** Task description (Due: MM-DD)' || char(10) || '- [ ] **[Owner]** Task description (Due: MM-DD)' || char(10) || '', content_json = '{"type":"doc","content":[]}' WHERE id = workspace_id || '_template_meeting' AND name = '会议纪要' AND title = '会议纪要' AND description = '结构化记录议题背景、核心结论与带负责人的待办事项。' AND content_markdown = '# 📝 会议纪要' || char(10) || '' || char(10) || '- **时间**：' || char(10) || '- **主持人/记录人**：' || char(10) || '- **参会人**：' || char(10) || '' || char(10) || '---' || char(10) || '' || char(10) || '## 🎯 会议目标' || char(10) || '' || char(10) || '- ' || char(10) || '' || char(10) || '## 💬 核心讨论与决策' || char(10) || '' || char(10) || '1. **[议题 1]**' || char(10) || '   - 讨论要点：' || char(10) || '   - ✅ **决议**：' || char(10) || '' || char(10) || '2. **[议题 2]**' || char(10) || '   - 讨论要点：' || char(10) || '   - ✅ **决议**：' || char(10) || '' || char(10) || '## 📋 待办事项 (Action Items)' || char(10) || '' || char(10) || '- [ ] **[负责人]** 任务描述 (截止日期：MM-DD)' || char(10) || '- [ ] **[负责人]** 任务描述 (截止日期：MM-DD)' || char(10) || '' AND updated_at = created_at;

UPDATE memo_templates SET name = 'Weekly Review & Status', title = 'Weekly Review & Status', description = 'Summarize weekly highlights, blockers, and next week''s key priorities.', content_markdown = '# 🗓️ Weekly Status Report' || char(10) || '' || char(10) || '## 🌟 Highlights' || char(10) || '' || char(10) || '- [x] **[Project/Feature]** Accomplishment details' || char(10) || '- [x] **[Project/Feature]** Accomplishment details' || char(10) || '' || char(10) || '## 🚧 Blockers & Risks' || char(10) || '' || char(10) || '- ⚠️ **Blocker**: Reason and required support' || char(10) || '' || char(10) || '## 🎯 Next Week Priorities' || char(10) || '' || char(10) || '- [ ] ' || char(10) || '- [ ] ' || char(10) || '- [ ] ' || char(10) || '' || char(10) || '## 💡 Reflection & Insights' || char(10) || '' || char(10) || '- ' || char(10) || '', content_json = '{"type":"doc","content":[]}' WHERE id = workspace_id || '_template_weekly-review' AND name = '周报与进展复盘' AND title = '周报与进展复盘' AND description = '梳理本周核心产出、风险卡点与下周关键优先级。' AND content_markdown = '# 🗓️ 工作周报' || char(10) || '' || char(10) || '## 🌟 本周核心进展 (Highlights)' || char(10) || '' || char(10) || '- [x] **[项目/功能]** 完成情况与成果说明' || char(10) || '- [x] **[项目/功能]** 完成情况与成果说明' || char(10) || '' || char(10) || '## 🚧 卡点与风险 (Blockers & Risks)' || char(10) || '' || char(10) || '- ⚠️ **阻塞项**：原因及所需支持' || char(10) || '' || char(10) || '## 🎯 下周优先级 (Next Week Priorities)' || char(10) || '' || char(10) || '- [ ] ' || char(10) || '- [ ] ' || char(10) || '- [ ] ' || char(10) || '' || char(10) || '## 💡 总结与思考' || char(10) || '' || char(10) || '- ' || char(10) || '' AND updated_at = created_at;

UPDATE memo_templates SET name = 'Reading Note Card', title = 'Reading Note Card', description = 'Extract key takeaways, quotes, reflections, and connected concepts.', content_markdown = '# 📖 Reading Note Card' || char(10) || '' || char(10) || '- **Book/Article**:' || char(10) || '- **Author/Source**:' || char(10) || '- **Rating**: ⭐⭐⭐⭐⭐' || char(10) || '' || char(10) || '---' || char(10) || '' || char(10) || '## 💡 Key Takeaway' || char(10) || '' || char(10) || '> ' || char(10) || '' || char(10) || '## ✍️ Highlights & Quotes' || char(10) || '' || char(10) || '> [Quote content]' || char(10) || '> —— *Original Source*' || char(10) || '' || char(10) || '## 🧠 Personal Reflections' || char(10) || '' || char(10) || '- ' || char(10) || '' || char(10) || '## 🔗 Action & Practice' || char(10) || '' || char(10) || '- [ ] **Action Plan**:' || char(10) || '', content_json = '{"type":"doc","content":[]}' WHERE id = workspace_id || '_template_reading' AND name = '深度阅读卡片' AND title = '深度阅读卡片' AND description = '提炼核心观点、精妙摘录、个人理解与关联知识卡片。' AND content_markdown = '# 📖 深度阅读卡片' || char(10) || '' || char(10) || '- **书名/文章**：' || char(10) || '- **作者/来源**：' || char(10) || '- **推荐指数**：⭐⭐⭐⭐⭐' || char(10) || '' || char(10) || '---' || char(10) || '' || char(10) || '## 💡 一句话总结 (Key Takeaway)' || char(10) || '' || char(10) || '> ' || char(10) || '' || char(10) || '## ✍️ 核心观点与金句摘录' || char(10) || '' || char(10) || '> [摘录内容]' || char(10) || '> —— *原书/原文*' || char(10) || '' || char(10) || '## 🧠 我的理解与延伸思考' || char(10) || '' || char(10) || '- ' || char(10) || '' || char(10) || '## 🔗 关联知识与行动' || char(10) || '' || char(10) || '- [ ] **落地实践**：' || char(10) || '' AND updated_at = created_at;

UPDATE memo_templates SET name = 'Goal & Task Breakdown', title = 'Goal & Task Breakdown', description = 'Define OKRs, Key Results, milestones, and task checklists.', content_markdown = '# 🎯 Goal Breakdown' || char(10) || '' || char(10) || '- **Period**:' || char(10) || '- **Owner**:' || char(10) || '' || char(10) || '---' || char(10) || '' || char(10) || '## 📌 Objective' || char(10) || '' || char(10) || '> ' || char(10) || '' || char(10) || '## 📈 Key Results' || char(10) || '' || char(10) || '- **KR 1**: Target metric -> Current progress' || char(10) || '- **KR 2**: Target metric -> Current progress' || char(10) || '' || char(10) || '## 🗓️ Milestones' || char(10) || '' || char(10) || '- [ ] **Phase 1 (Date)**: Target' || char(10) || '- [ ] **Phase 2 (Date)**: Target' || char(10) || '' || char(10) || '## 📋 Execution Checklist' || char(10) || '' || char(10) || '- [ ] ' || char(10) || '- [ ] ' || char(10) || '', content_json = '{"type":"doc","content":[]}' WHERE id = workspace_id || '_template_okr' AND name = '目标与任务拆解' AND title = '目标与任务拆解' AND description = '明确 OKR 目标、关键结果、里程碑与具体执行清单。' AND content_markdown = '# 🎯 目标拆解' || char(10) || '' || char(10) || '- **周期**：' || char(10) || '- **负责人**：' || char(10) || '' || char(10) || '---' || char(10) || '' || char(10) || '## 📌 目标 (Objective)' || char(10) || '' || char(10) || '> ' || char(10) || '' || char(10) || '## 📈 关键结果 (Key Results)' || char(10) || '' || char(10) || '- **KR 1**：期望指标 -> 当前进度' || char(10) || '- **KR 2**：期望指标 -> 当前进度' || char(10) || '' || char(10) || '## 🗓️ 里程碑节点 (Milestones)' || char(10) || '' || char(10) || '- [ ] **阶段一 (日期)**：完成标的' || char(10) || '- [ ] **阶段二 (日期)**：完成标的' || char(10) || '' || char(10) || '## 📋 执行任务清单' || char(10) || '' || char(10) || '- [ ] ' || char(10) || '- [ ] ' || char(10) || '' AND updated_at = created_at;

UPDATE ai_prompt_templates SET name = CASE WHEN name_customized = 0 THEN 'Summarize' ELSE name END, description = CASE WHEN description_customized = 0 THEN 'Condense the note into its topic, conclusions, and actionable outcomes' ELSE description END, instruction = CASE WHEN instruction_customized = 0 THEN 'Create a genuinely condensed summary of the note rather than rewriting, paraphrasing line by line, or echoing it. Identify the central topic, main claims, essential conclusions, and actionable outcomes. Omit repetition, rhetorical phrasing, examples, quotations, and minor details unless necessary to understand a key conclusion. For a substantial note, target roughly 20–30% of the source length and use 3–7 concise Markdown bullet points; for a short note, use 1–3 concise sentences. Do not reproduce long passages verbatim or add facts that are not present in the source. Preserve the note''s language and return only the summary in Markdown.' ELSE instruction END WHERE seed_key = 'summarize';

UPDATE ai_prompt_templates SET name = CASE WHEN name_customized = 0 THEN 'Translate' ELSE name END, description = CASE WHEN description_customized = 0 THEN 'Translate into a selected language while preserving formatting' ELSE description END, instruction = CASE WHEN instruction_customized = 0 THEN 'Translate the complete note into the target language specified by the user. Preserve its meaning, Markdown structure, links, and code blocks. Return only the translated note without commentary.' ELSE instruction END WHERE seed_key = 'translate';

UPDATE ai_prompt_templates SET name = CASE WHEN name_customized = 0 THEN 'Polish' ELSE name END, description = CASE WHEN description_customized = 0 THEN 'Correct the language and improve clarity and flow' ELSE description END, instruction = CASE WHEN instruction_customized = 0 THEN 'Polish the content by correcting spelling, grammar, and punctuation and improving word choice, sentence structure, clarity, and flow. Do not change its meaning or deliberately shorten it. Preserve its language and useful Markdown formatting. Return only the polished content.' ELSE instruction END WHERE seed_key = 'improve-writing';

UPDATE ai_prompt_templates SET name = CASE WHEN name_customized = 0 THEN 'Make concise' ELSE name END, description = CASE WHEN description_customized = 0 THEN 'Remove repetition and make the writing concise and direct' ELSE description END, instruction = CASE WHEN instruction_customized = 0 THEN 'Refine the content by removing repetition, filler, and unnecessary modifiers and by combining sentences where useful. Make it concise, clear, and direct while preserving every key fact, claim, and the original meaning. Do not add new information. Preserve its language and useful Markdown formatting. Return only the refined content.' ELSE instruction END WHERE seed_key = 'make-shorter';

UPDATE ai_prompt_templates SET name = CASE WHEN name_customized = 0 THEN 'Extract tasks' ELSE name END, description = CASE WHEN description_customized = 0 THEN 'Identify actionable work and produce a task list' ELSE description END, instruction = CASE WHEN instruction_customized = 0 THEN 'Extract explicit or implied actionable tasks from the note as a Markdown task list using ''- [ ]''. Preserve its language and do not invent tasks. If there are no actionable tasks, say so briefly in the note''s language.' ELSE instruction END WHERE seed_key = 'extract-todos';

UPDATE ai_prompt_templates SET name = CASE WHEN name_customized = 0 THEN 'Continue writing' ELSE name END, description = CASE WHEN description_customized = 0 THEN 'Continue naturally from the end of the note' ELSE description END, instruction = CASE WHEN instruction_customized = 0 THEN 'Continue writing naturally from where the note ends. Return only the new continuation, not the original content. Preserve its language and Markdown style.' ELSE instruction END WHERE seed_key = 'continue-writing';

-- Translate the original welcome note only when its body is untouched and active.
UPDATE memo_contents SET content_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Welcome to EdgeEver"}]},{"type":"paragraph","content":[{"type":"text","text":"Your first EdgeEver note: three panes, edge-powered, and Agent-ready."}]},{"type":"paragraph","content":[{"type":"text","text":"Create notebooks, write notes, search your content, and merge related notes into a lasting reference."}]}]}', content_markdown = '## Welcome to EdgeEver' || char(10) || '' || char(10) || 'Your first EdgeEver note: three panes, edge-powered, and Agent-ready.' || char(10) || '' || char(10) || 'Create notebooks, write notes, search your content, and merge related notes into a lasting reference.', content_text = 'Welcome to EdgeEver Your first EdgeEver note: three panes, edge-powered, and Agent-ready. Create notebooks, write notes, search your content, and merge related notes into a lasting reference.', content_hash = '9d0c409e3d8fe99e7db91a73c123fc0bd3fbd93575f5a19b660c15bc81c31ebd'
WHERE memo_id = 'memo_welcome' AND revision = 0 AND content_json = '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"欢迎来到 EdgeEver"}]},{"type":"paragraph","content":[{"type":"text","text":"这是第一条 EdgeEver 笔记，三栏、边缘、Agent-ready。"}]},{"type":"paragraph","content":[{"type":"text","text":"接下来可以创建笔记本、写笔记、搜索内容，并把多条笔记合并成一条新的长期笔记。"}]}]}'
  AND EXISTS (SELECT 1 FROM memos WHERE id = 'memo_welcome' AND title = '欢迎来到 EdgeEver' AND updated_by = 'system' AND is_deleted = 0);
UPDATE memos SET title = 'Welcome to EdgeEver', excerpt = 'Your first EdgeEver note: three panes, edge-powered, and Agent-ready.'
WHERE id = 'memo_welcome' AND title = '欢迎来到 EdgeEver' AND updated_by = 'system' AND is_deleted = 0
  AND EXISTS (SELECT 1 FROM memo_contents WHERE memo_id = 'memo_welcome' AND content_hash = '9d0c409e3d8fe99e7db91a73c123fc0bd3fbd93575f5a19b660c15bc81c31ebd');
UPDATE memos SET title = 'Untitled note' WHERE title = '无标题笔记';
UPDATE memo_search_documents SET title = (SELECT title FROM memos WHERE id = memo_id), content_text = (SELECT content_text FROM memo_contents WHERE memo_id = memo_search_documents.memo_id)
WHERE memo_id = 'memo_welcome' AND EXISTS (SELECT 1 FROM memo_contents WHERE memo_id = 'memo_welcome' AND content_hash = '9d0c409e3d8fe99e7db91a73c123fc0bd3fbd93575f5a19b660c15bc81c31ebd');
UPDATE memo_search_documents SET title = 'Untitled note' WHERE title = '无标题笔记';
